<?php
//$Id: adsense_click.module,v 1.2.2.9 2008/11/09 17:30:42 kbahey Exp $

define('ADSENSE_CLICK_TRACKING',              'adsense_click_tracking');
define('ADSENSE_CLICK_TRACKING_NAME_RESOLVE', 'adsense_click_tracking_name_resolve');

/**
 * Implementation of hook_menu().
 */
function adsense_click_menu() {
  $items = array();

  $items['admin/settings/adsense/click'] = array(
    'title'            => t('Clicks'),
    'description'      => t('Track the clicks on Adsense ads.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('adsense_click_admin_settings'),
    'type'             => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
  );

  $access = array('view clicks');

  $items['admin/reports/adsense'] = array(
    'title'            => t('AdSense clicks'),
    'description'      => t('Track AdSense clicks.'),
    'page callback'    => 'adsense_click_log',
    'type'             => MENU_NORMAL_ITEM,
    'access arguments' => $access,
  );

  $items['admin/reports/adsense/top_pages'] = array(
    'title'            => t('Top pages'),
    'page callback'    => 'adsense_click_top_pages',
    'type'             => MENU_NORMAL_ITEM,
    'access arguments' => $access,
  );

  $items['admin/reports/adsense/by_day'] = array(
    'title'            => t('By day'),
    'page callback'    => 'adsense_click_by_day',
    'type'             => MENU_NORMAL_ITEM,
    'access arguments' => $access,
  );

  $items['adsense_click'] = array(
    'page callback'    => 'adsense_click_register',
    'type'             => MENU_CALLBACK,
    'access callback'  => TRUE,
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function adsense_click_perm() {
  return array('view clicks');
}

function adsense_click_admin_settings() {
  $form['click_tracking'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Click tracking'),
  );

  $form['click_tracking'][ADSENSE_CLICK_TRACKING] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Enable AdSense click tracking?'),
    '#return_value'  => 1,
    '#default_value' => variable_get(ADSENSE_CLICK_TRACKING, TRUE),
    '#description'   => t('Logs IP and time of <a href=!url>AdSense clicks</a>. This can be very useful in tracking which of your pages generate the most clicks, as well as help if click fraud is suspected.', array('!url' => url('admin/reports/adsense'))),
  );

  $form['click_tracking'][ADSENSE_CLICK_TRACKING_NAME_RESOLVE] = array(
    '#type'          => 'checkbox',
    '#title'         => t('Enable name resolution of IP addresses?'),
    '#return_value'  => 1,
    '#default_value' => variable_get(ADSENSE_CLICK_TRACKING_NAME_RESOLVE, 0),
    '#description'   => t('Display the domain name instead of the IP address. This can slow down the display of the logs page and tie up a PHP process for several seconds. On some hosting providers it may not be available.'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_footer().
 */
function adsense_click_footer($main = 0) {
  global $base_url;

  if (variable_get(ADSENSE_CLICK_TRACKING, TRUE)) {
    $path = base_path() . drupal_get_path('module', 'adsense_click') .'/adsense_click.js';
    $js = '<script type="text/javascript" src="'. $path .'"></script>';
    return $js;
  }
}

function adsense_click_register() {
  if (variable_get(ADSENSE_CLICK_TRACKING, TRUE)) {
    db_query("INSERT INTO {adsense_clicks} (ip, timestamp, path, title, referrer) values('%s', %d, '%s', '%s', '%s')",
      $_SERVER['REMOTE_ADDR'], time(), $_GET['u'], $_GET['t'], $_GET['r']);
  }
}

function adsense_click_log() {
  $header = array(
    array('data' => t('Timestamp'), 'field' => 'timestamp', 'sort' => 'desc'),
    array('data' => t('Path'),      'field' => 'path'),
    array('data' => t('IP/Host'),   'field' => 'ip'),
    array('data' => t('Referrer'),  'field' => 'referrer'),
  );

  $name_resolve = variable_get(ADSENSE_CLICK_TRACKING_NAME_RESOLVE, 0);

  $sql = 'SELECT * FROM {adsense_clicks} '. tablesort_sql($header);

  $result = pager_query($sql, 50);
  while ($log = db_fetch_object($result)) {
    if ($name_resolve) {
      $host = gethostbyaddr($log->ip);
    }
    else {
      $host = $log->ip;
    }

    $rows[] = array(
      array('data' => format_date($log->timestamp, 'small'), 'nowrap' => 'nowrap'),
      _adsense_click_format_path($log->path, $log->title),
      l($host, 'http://whois.domaintools.com/'. $log->ip),
      _adsense_click_format_path($log->referrer),
    );
  }

  return theme('table', $header, $rows) . theme('pager', NULL, 50, 0);
}

function adsense_click_top_pages() {
  $header = array(
    array('data' => t('Path'),   'field' => 'path'),
    array('data' => t('Clicks'), 'field' => 'count', 'sort' => 'desc'),
    array('data' => t('Last'),   'field' => 'last'),
  );

  $sql = 'SELECT path, COUNT(*) AS count, MAX(timestamp) AS last FROM {adsense_clicks} GROUP BY path'. tablesort_sql($header);

  $result = pager_query($sql, 50);
  while ($log = db_fetch_object($result)) {
    $title = db_result(db_query("SELECT title FROM {adsense_clicks} WHERE path = '%s'", $path));
    $rows[] = array(
      array('data' => _adsense_click_format_path($log->path, $title)),
      array('data' => $log->count, 'align' => 'right'),
      array('data' => format_date($log->last, 'small'), 'nowrap' => 'nowrap'),
    );
  }

  return theme('table', $header, $rows) . theme('pager', NULL, 50, 0);
}

function adsense_click_by_day() {
  global $db_type;
  $header = array(
    array('data' => t('Day'),    'field' => 'day', 'sort' => 'desc'),
    array('data' => t('Clicks'), 'field' => 'count'),
  );

  switch ($db_type) {
    case 'mysql':
    case 'mysqli':
      $sql_count = "SELECT COUNT(DISTINCT(FROM_UNIXTIME(timestamp, '%y-%m-%%d'))) FROM {adsense_clicks}";
      $sql = "SELECT FROM_UNIXTIME(timestamp, '%Y-%m-%%d') AS day, COUNT(*) AS count FROM {adsense_clicks} GROUP BY day" . tablesort_sql($header);
      break;
    case 'pgsql':
      $sql_count = "SELECT COUNT(DISTINCT(TO_CHAR(timestamp, 'YYYY-MM-DD'))) FROM {adsense_clicks}";
      $sql = "SELECT TO_CHAR(timestamp, 'YYYY-MM-DD') AS day, COUNT(*) AS count FROM {adsense_clicks} GROUP BY day" . tablesort_sql($header);
      break;
  }

  $result = pager_query($sql, 50, 0, $sql_count);
  while ($log = db_fetch_object($result)) {
    $rows[] = array(
      $log->day,
      array('data' => $log->count, 'align' => 'right'),
    );
  }

  return theme('table', $header, $rows) . theme('pager', NULL, 50, 0);
}

function _adsense_click_format_path($path, $title = '', $width = 32) {
  global $base_url;

  if ($title) {
    $short_title = truncate_utf8($title, $width, FALSE, TRUE);
  }
  else {
    $title = $path;
    $short_path = preg_replace('?^' . $base_url. '?', '', $path);
    $short_title = truncate_utf8($short_path, $width, FALSE, TRUE);
  }

  return l($short_title, $path, array('title' => $title));
}
