<?php
// $Id: googlesearch.module,v 1.1 2006/08/27 09:59:52 crell Exp $

/** 
  * Implementation of hook_help(). 
  */
function googlesearch_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      // This description is shown in the listing at admin/modules.
      return t('Lets users easily search a site with %sitesearch.', array('%sitesearch' => l('Google SiteSearch', 'http://www.google.com/searchcode.html')));
  }
}


/** 
  * Implementation of hook_block(). 
  */
function googlesearch_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['sitesearch'] = array(
      'info' => t('Google SiteSearch'),
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch($delta) {
      case 'sitesearch':
        $block = array(
          'subject' => t('Google Search'),
          'content' => googlesearch_block_sitesearch(),
         );
        return $block;
        break;
    }
  }
}



function googlesearch_block_sitesearch() {
  $form = array();

  $logo = theme('image', 'http://www.google.com/logos/Logo_25wht.gif', 'Google', 'Google', NULL, FALSE);

  $form['#action'] = 'http://www.google.com/search';
  $form['#method'] = 'get';
  $form['ie'] = array(
    '#name' => 'ie',
    '#type' => 'hidden',
    '#value' => 'UTF-8',
  );
  $form['oe'] = array(
    '#name' => 'oe',
    '#type' => 'hidden',
    '#value' => 'UTF-8',
  );
  $form['domains'] = array(
    '#name' => 'domains',
    '#type' => 'hidden',
    '#value' => $_SERVER['SERVER_NAME'],
  );
  $form['sitesearch'] = array(
    '#name' => 'sitesearch',
    '#type' => 'hidden',
    '#value' => $_SERVER['SERVER_NAME'],
  );
  $form['google'] = array(
    '#type' => 'markup',
    '#value' => l($logo, 'http://www.google.com/', array(), NULL, NULL, TRUE, TRUE),
  );
  $form['q'] = array(
    '#name' => 'q',
    '#type' => 'textfield', 
    '#title' => t('Google Search'), 
    '#size' => 20,
    '#maxlength' => 255,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search')
  );

  return drupal_get_form('googlesearch_sitesearch', $form);
}


function theme_googlesearch_sitesearch($form) {
  $output = '';

  // This is redundant with the title of the block
  $form['q']['#title'] = '';

  $output .= form_render($form);

  return $output;
}
