<?php
//$Id: revenue_sharing_basic.module,v 1.4.2.3 2008/09/11 22:52:00 jcnventura Exp $
// Copyright 2005-2008 Khalid Baheyeldin http://2bits.com

/**
 * @file
 * Main file of the revenue_sharing_basic module
 */

define('REVENUE_SHARING_BASIC_CLIENT_ID_PROFILE_FIELD_DEFAULT', 0);
define('REVENUE_SHARING_BASIC_PERCENTAGE_AUTHOR_DEFAULT', 0);
define('REVENUE_SHARING_BASIC_PERCENTAGE_REFER_DEFAULT', 0);
define('REVENUE_SHARING_BASIC_REVENUE_ENABLE_DEFAULT', 0);

/**
 * Implementation of hook_menu().
 */
function revenue_sharing_basic_menu() {
  $items = array();

  $items['admin/settings/adsense/id/revenue_sharing_basic'] = array(
    'title' => 'Basic Revenue Sharing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('revenue_sharing_basic_settings'),
    'access arguments' => array('administer adsense'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'revenue_sharing_basic.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_requirements().
 */
function revenue_sharing_basic_requirements($phase) {
  $requirements = array();
  $t = get_t();
  switch ($phase) {
    // At runtime, make sure that we have a publisher ID
    case 'runtime':
      if (variable_get('cache', 0)) {
        $requirements['adsense_basic_id'] = array(
          'title' => $t('Revenue Sharing (basic)'),
          'value' => $t('Drupal page cache is enabled. This causes conflicts with revenue sharing, since the pages are stored in the cache and are not dynamically generated. If you experience issues with revenue sharing, then disable the page cache.'),
          'severity' => REQUIREMENT_WARNING,
        );
      }
      break;
  }
  return $requirements;
}

/**
 * Interface of the Publisher ID modules
 *
 * This is the function that handles the calls by the adsense core to the
 * Publisher ID modules
 *
 * @param $op
 *   Operation being performed, can be one of the following:
 *   'settings' : access to this module's settings form
 *   'client_id': fetch the user's Publisher ID
 * @param $args
 *   For the 'client_id' operation, this can be the format of the ad being
 *   generated, in case there is a need to return a user-configured Slot ID
 * @return
 *   This depends on the operation being performed:
 *   'settings':   return array with two fields, the name field contains the
 *                 name of this module, and the desc field a description.
 *   'client_id' : this can be a string with the publisher ID, when the
 *                 $args parameter wasn't defined, or an array with two
 *                 fields, the 'slot' field for the Slot ID and the 'client'
 *                 field for the Publisher ID
 */
function revenue_sharing_basic_adsense($op, $args = array()) {
  static $client_id = NULL;

  switch ($op) {
    case 'settings':
        return array(
          'name' => 'Revenue sharing (basic)',
          'desc' => 'DOES NOT WORK with new code ad units, such as "Managed Ads" or "Custom Search".',
        );
      break;
    case 'client_id':
      if (!$client_id) {
        // We cache the client ID on this page load, to make sure all of the
        // client IDs on one page are the same
        $client_id = revenue_sharing_basic_choose_client($args);
      }

      return $client_id;
  }
}

/**
 * Provide the applicable Publisher ID, based on the configured probabilities
 *
 * @param $format
 *   Format of the ad
 * @return
 *   If format is set, returns NULL. Otherwise, based on the configured 
 *   percentage, returns either the Publisher ID of the current page's author
 *   or of the owner of the site. When configured, it may also return the
 *   Publisher ID of the user who referred the page author.
 */
function revenue_sharing_basic_choose_client($format) {
  if (isset($format)) {
    // This module can't handle the selection of an appropriate Slot ID
    // Give up!
    return NULL;
  }

  $site_client = variable_get('adsense_basic_id', ADSENSE_BASIC_ID_DEFAULT);

  if (!variable_get('revenue_sharing_basic_revenue_enable', REVENUE_SHARING_BASIC_REVENUE_ENABLE_DEFAULT)) {
    return $site_client;
  }

  $uid = revenue_sharing_basic_get_node_uid();
  $percent_author   = variable_get('revenue_sharing_basic_percentage_author', REVENUE_SHARING_BASIC_PERCENTAGE_AUTHOR_DEFAULT);
  $percent_referral = variable_get('revenue_sharing_basic_percentage_refer', REVENUE_SHARING_BASIC_PERCENTAGE_REFER_DEFAULT);

  // Toss the dice and see who gets their ad displayed
  $random = mt_rand(1, 100);
  if ($random <= $percent_author) {
    $client = revenue_sharing_basic_get_profile_client_id($uid);
  }
  elseif ($random <= ($percent_author + $percent_referral)) {
    $client = revenue_sharing_basic_get_referral_client_id($uid);
  }
  else {
    $client = $site_client;
  }

  // Last check to see that we have a valid client
  if (!$client) {
    $client = $site_client;
  }

  return $client;
}

/**
 * Provide the Publisher ID of the the specified user
 *
 * @param $uid
 *   User ID
 * @return
 *   Publisher ID of the specified user in case it applies, otherwise NULL
 */
function revenue_sharing_basic_get_profile_client_id($uid) {
  $client_id = NULL;

  if ($uid) {
    // Get the profile field for a certain user
    $profile_field = variable_get('revenue_sharing_basic_client_id_profile_field', REVENUE_SHARING_BASIC_CLIENT_ID_PROFILE_FIELD_DEFAULT);
    $client_id = db_result(db_query('SELECT value FROM {profile_values} WHERE fid = %d AND uid = %d', $profile_field, $uid));
  }

  return $client_id;
}

/**
 * Provide the User ID of the author of the current page
 *
 * @return
 *   User ID of author, or NULL if it wasn't possible to discover one
 */
function revenue_sharing_basic_get_node_uid() {
  static $node_uid = NULL;

  if ((!$node_uid) && (arg(0) == 'node') && is_numeric(arg(1))) {
    $node = node_load(arg(1));

    // Cache the results
    $node_uid = $node->uid;
  }

  return $node_uid;
}

/**
 * Provide the Publisher ID of the user of referred the specified user
 *
 * @param $uid
 *   User ID
 * @return
 *   Publisher ID of the referrer of the specified user in case it applies,
 *   otherwise NULL
 */
function revenue_sharing_basic_get_referral_client_id($uid) {
  if (module_exists('referral')) {
    $referral_uid = referral_get_user($uid);
    if ($referral_uid) {
      return revenue_sharing_basic_get_profile_client_id($referral_uid);
    }
  }
  // User was not referred by an existing user
  return NULL;
}
